# Generated by Django 5.1.1 on 2024-11-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
