# Generated by Django 5.1.1 on 2024-10-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='cover_pictures/default.png', null=True, upload_to='cover_pictures/'),
        ),
    ]
